### ISSUE TITLE
document 생성시 날짜 자동 입력

### ISSUE THREAD

**Issue by june2** [kinnjoo/PROJECT_blog-backend-server#1]
https://github.com/kinnjoo/PROJECT_BlogBackendServer/blob/d7ee04ee4da53ca3d23881ce9bacbb48197b1fa2/routes/comments.js#L34

mongoose schema 에서 날짜를 default로 설정할수가 있는데요. 
그러면 코드에서  const createdAt = new Date(); 을 할당안해줘도 되요!
아래 문서 참고해보세요!
https://domdom.tistory.com/100

**Comment by kinnjoo** [comment]
감사합니다! 참고해서 수정하였습니다
