### ISSUE TITLE
findById

### ISSUE THREAD

**Issue by june2** [kinnjoo/PROJECT_blog-backend-server#3]
https://github.com/kinnjoo/PROJECT_BlogBackendServer/blob/d7ee04ee4da53ca3d23881ce9bacbb48197b1fa2/routes/posts.js#LL30C46-L30C46

위함수는 리스트로 반환하는데요 단건조회가 되어야하니 아래처럼 findOne 또는 findById를 사용해야되요!

```
findById(id)
```

**Comment by kinnjoo** [comment]
findOne으로 수정하였습니다!
