### ISSUE TITLE
404 에러

### ISSUE THREAD

**Issue by june2** [kinnjoo/PROJECT_blog-backend-server#4]
https://github.com/kinnjoo/PROJECT_BlogBackendServer/blob/d7ee04ee4da53ca3d23881ce9bacbb48197b1fa2/routes/posts.js#LL96C30-L96C34

조회 존재하지 않을시에는 404입니다~
<img width="362" alt="image" src="https://github.com/kinnjoo/PROJECT_BlogBackendServer/assets/5827617/2dabaa28-8e41-4052-8527-8e8a88c2ba13">

**Comment by kinnjoo** [comment]
조회 실패 오류는 404로 수정하였습니다!
